// بيانات الكتب
const booksData = [
    {
        id: 1,
        title: "تفسير القرآن العظيم",
        author: "ابن كثير",
        category: "quran",
        categoryName: "القرآن وعلومه",
        pages: 2400,
        rating: 4.9,
        downloads: 15000,
        description: "تفسير القرآن العظيم المشهور بتفسير ابن كثير، من أشهر كتب التفسير بالمأثور، يعتمد على تفسير القرآن بالقرآن والسنة النبوية وأقوال الصحابة والتابعين.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "الأكثر مبيعاً",
        publishYear: "1999",
        publisher: "دار طيبة",
        pdfFile: "books/tafsir-ibn-kathir.pdf"
    },
    {
        id: 2,
        title: "صحيح البخاري",
        author: "الإمام البخاري",
        category: "hadith",
        categoryName: "الحديث وعلومه",
        pages: 1800,
        rating: 5.0,
        downloads: 20000,
        description: "الجامع المسند الصحيح المختصر من أمور رسول الله صلى الله عليه وسلم وسننه وأيامه، أصح كتاب بعد كتاب الله تعالى.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "موثوق",
        publishYear: "2002",
        publisher: "دار السلام"
    },
    {
        id: 3,
        title: "رياض الصالحين",
        author: "يحي بن شرف النووي الدمشقي أبو زكريا",
        category: "hadith",
        categoryName: "الحديث وعلومه",
        pages: 680,
        rating: 4.5,
        downloads: 6988,
        description: "كتاب مختصر جمعه المصنف من الأحاديث الصحيحة، مشتملًا على ما يكون طريقًا لصاحبه إلى الآخرة جامعًا للترغيب والترهيب والزهد ورياضات النفوس، وقد التزم فيه أن لا يذكر إلا الأحاديث الصحيحة، وأحاديثه في مواضيع مختلفة مثل: العبادات، والمعاملات، والعادات، بحيث يصدر المؤلف جملة الأحاديث بعنوان لما تتضمنه الأحاديث بحيث يكون بابا لتلك الأحاديث.",
        cover: "images/covers/FQUkuw51rn7v4BsNsxDmypYz3APIBqNXixv8MOZa.jpg",
        badge: "جديد",
        publishYear: "2025",
        publisher: "دار ابن الجوزي",
        pdfFile: "books/RiyadUsSaliheen.pdf"
    },
    {
        id: 4,
        title: "فقه السنة",
        author: "السيد سابق",
        category: "fiqh",
        categoryName: "الفقه وأصوله",
        pages: 1200,
        rating: 4.7,
        downloads: 12000,
        description: "موسوعة فقهية شاملة تعرض أحكام الفقه الإسلامي بأسلوب سهل ميسر مع ذكر الأدلة من الكتاب والسنة.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "",
        publishYear: "2008",
        publisher: "دار الفتح"
    },
    {
        id: 5,
        title: "العقيدة الطحاوية",
        author: "الإمام الطحاوي",
        category: "aqeedah",
        categoryName: "العقيدة",
        pages: 300,
        rating: 4.9,
        downloads: 10000,
        description: "متن مختصر في بيان عقيدة أهل السنة والجماعة، يعد من أهم المتون في العقيدة الإسلامية.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "مميز",
        publishYear: "2005",
        publisher: "دار البشائر"
    },
    {
        id: 6,
        title: "الرحيق المختوم",
        author: "صفي الرحمن المباركفوري",
        category: "seerah",
        categoryName: "السيرة النبوية",
        pages: 500,
        rating: 4.9,
        downloads: 16000,
        description: "بحث في السيرة النبوية على صاحبها أفضل الصلاة والسلام، فاز بالجائزة الأولى في مسابقة رابطة العالم الإسلامي.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "الأكثر مبيعاً",
        publishYear: "2006",
        publisher: "دار الوفاء"
    },
    {
        id: 7,
        title: "الأذكار",
        author: "الإمام النووي",
        category: "akhlaq",
        categoryName: "الأخلاق والآداب",
        pages: 400,
        rating: 4.8,
        downloads: 14000,
        description: "كتاب جامع للأذكار والأدعية المأثورة عن النبي صلى الله عليه وسلم في مختلف الأحوال والأوقات.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "",
        publishYear: "2007",
        publisher: "دار المنهاج"
    },
    {
        id: 8,
        title: "زاد المعاد",
        author: "ابن القيم الجوزية",
        category: "seerah",
        categoryName: "السيرة النبوية",
        pages: 1500,
        rating: 4.9,
        downloads: 11000,
        description: "موسوعة شاملة في هدي النبي صلى الله عليه وسلم في جميع شؤون الحياة، من أنفع الكتب في بابها.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "مميز",
        publishYear: "2009",
        publisher: "مؤسسة الرسالة"
    },
    {
        id: 9,
        title: "تيسير الكريم الرحمن",
        author: "عبد الرحمن السعدي",
        category: "quran",
        categoryName: "القرآن وعلومه",
        pages: 1000,
        rating: 4.8,
        downloads: 13000,
        description: "تفسير مختصر وواضح للقرآن الكريم، يتميز بسهولة العبارة ووضوح المعنى مع الاختصار المفيد.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "جديد",
        publishYear: "2011",
        publisher: "دار ابن الجوزي"
    },
    {
        id: 10,
        title: "الموطأ",
        author: "الإمام مالك",
        category: "hadith",
        categoryName: "الحديث وعلومه",
        pages: 800,
        rating: 4.7,
        downloads: 9000,
        description: "أول كتاب جامع في الحديث النبوي والفقه، من أصح الكتب بعد الصحيحين.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "",
        publishYear: "2004",
        publisher: "دار الغرب الإسلامي"
    },
    {
        id: 11,
        title: "الفقه الميسر",
        author: "مجموعة من العلماء",
        category: "fiqh",
        categoryName: "الفقه وأصوله",
        pages: 700,
        rating: 4.6,
        downloads: 10500,
        description: "كتاب في الفقه الإسلامي بأسلوب سهل ميسر، يعرض الأحكام الفقهية بطريقة واضحة ومبسطة.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "",
        publishYear: "2012",
        publisher: "مدار الوطن"
    },
    {
        id: 12,
        title: "شرح العقيدة الواسطية",
        author: "محمد بن صالح العثيمين",
        category: "aqeedah",
        categoryName: "العقيدة",
        pages: 450,
        rating: 4.8,
        downloads: 8500,
        description: "شرح مفصل لمتن العقيدة الواسطية لشيخ الإسلام ابن تيمية، بأسلوب واضح ومنهج علمي دقيق.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "مميز",
        publishYear: "2008",
        publisher: "دار ابن الجوزي"
    },
    {
        id: 13,
        title: "البداية والنهاية",
        author: "ابن كثير",
        category: "history",
        categoryName: "التاريخ الإسلامي",
        pages: 3000,
        rating: 4.9,
        downloads: 12500,
        description: "موسوعة تاريخية ضخمة تبدأ من بدء الخلق وتنتهي بأحداث القرن الثامن الهجري، من أهم المراجع في التاريخ الإسلامي.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "الأكثر مبيعاً",
        publishYear: "2003",
        publisher: "دار هجر"
    },
    {
        id: 14,
        title: "إحياء علوم الدين",
        author: "أبو حامد الغزالي",
        category: "akhlaq",
        categoryName: "الأخلاق والآداب",
        pages: 2000,
        rating: 4.7,
        downloads: 11500,
        description: "موسوعة في علوم الدين والأخلاق والتزكية، من أعظم الكتب في بابها.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "",
        publishYear: "2005",
        publisher: "دار المنهاج"
    },
    {
        id: 15,
        title: "الجامع لأحكام القرآن",
        author: "القرطبي",
        category: "quran",
        categoryName: "القرآن وعلومه",
        pages: 2200,
        rating: 4.8,
        downloads: 10000,
        description: "تفسير جامع للقرآن الكريم يعتني بالأحكام الفقهية المستنبطة من الآيات، مع بيان القراءات واللغة.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "جديد",
        publishYear: "2006",
        publisher: "مؤسسة الرسالة"
    },
    {
        id: 16,
        title: "الأربعون النووية",
        author: "الإمام النووي",
        category: "hadith",
        categoryName: "الحديث وعلومه",
        pages: 150,
        rating: 4.9,
        downloads: 17000,
        description: "مجموعة من اثنين وأربعين حديثاً نبوياً شريفاً، تدور حول أصول الإسلام وقواعده.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "الأكثر مبيعاً",
        publishYear: "2010",
        publisher: "دار ابن كثير"
    },
    {
        id: 17,
        title: "الفقه على المذاهب الأربعة",
        author: "عبد الرحمن الجزيري",
        category: "fiqh",
        categoryName: "الفقه وأصوله",
        pages: 1800,
        rating: 4.7,
        downloads: 9500,
        description: "موسوعة فقهية مقارنة تعرض الأحكام الفقهية على المذاهب الأربعة المعتمدة.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "",
        publishYear: "2007",
        publisher: "دار الحديث"
    },
    {
        id: 18,
        title: "كتاب التوحيد",
        author: "محمد بن عبد الوهاب",
        category: "aqeedah",
        categoryName: "العقيدة",
        pages: 200,
        rating: 4.8,
        downloads: 13500,
        description: "كتاب مختصر في بيان التوحيد وأنواعه وما يضاده من الشرك الأكبر والأصغر.",
        cover: "https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=400&h=600&fit=crop",
        badge: "مميز",
        publishYear: "2009",
        publisher: "دار الصميعي"
    }
];

// تصدير البيانات
if (typeof module !== 'undefined' && module.exports) {
    module.exports = booksData;
}